// Load all the controllers within this directory and all subdirectories. 
// Controller files must be named *_controller.js or *_controller.ts.
// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { Application } from "stimulus"
import { definitionsFromContext } from "stimulus/webpack-helpers"
import Autosave from "stimulus-rails-autosave"
import PlacesAutocomplete from "stimulus-places-autocomplete"
import { Slideover } from "tailwindcss-stimulus-components"
// import { application } from "./application"

const application = Application.start()
const context = require.context("controllers", true, /_controller\.(js|ts)$/)
const contextComponents = require.context("../../components", true, /_controller\.js$/)
application.load(definitionsFromContext(context).concat(definitionsFromContext(contextComponents)))
application.register("autosave", Autosave)
application.register("places", PlacesAutocomplete)
application.register('slideover', Slideover)
