// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoSubmit from '@stimulus-components/auto-submit'
application.register('auto-submit', AutoSubmit)

import { Slideover } from "tailwindcss-stimulus-components"
application.register('slideover', Slideover)

import AutoplacesController from "./autoplaces_controller"
application.register("autoplaces", AutoplacesController)

