// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import { definitionsFromContext } from "stimulus/webpack-helpers"
import Autosave from "stimulus-rails-autosave"
application.register("autosave", Autosave)

import { Slideover } from "tailwindcss-stimulus-components"
application.register('slideover', Slideover)

import AutoplacesController from "./autoplaces_controller"
application.register("autoplaces", AutoplacesController)

