require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'vendor/bundle/**/*'

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/AmbiguousBlockAssociation:
  AllowedMethods: [change]

Lint/MissingSuper:
  Exclude:
    - 'app/components/**/*'

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods: [describe, context, it, before, configure, task]
  Exclude:
    - 'config/routes.rb'

Naming/VariableNumber:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'config/application.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never

Style/GlobalStdStream:
  Exclude:
    - 'config/environments/*'

Style/RedundantFetchBlock:
  Exclude:
    - 'config/puma.rb'

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/OpenStructUse:
  Enabled: false
  
Layout/LineLength:
  Enabled: false

RSpec/ExampleLength:
  Max: 10
  CountAsOne: [array, hash, heredoc]
  Exclude:
    - 'spec/system/**'

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false
