require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'vendor/bundle/**/*'

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/AmbiguousBlockAssociation:
  IgnoredMethods: [change]

Lint/MissingSuper:
  Exclude:
    - 'app/components/**/*'

Metrics/BlockLength:
  IgnoredMethods: [describe, context, it, before, configure, task]

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'config/application.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never

Style/GlobalStdStream:
  Exclude:
    - 'config/environments/*'

Style/RedundantFetchBlock:
  Exclude:
    - 'config/puma.rb'

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Layout/LineLength:
  Max: 110
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'
    - 'db/**/*'

RSpec/ExampleLength:
  CountAsOne: [array, hash, heredoc]
  Exclude:
    - 'spec/system/**'

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/system/**/*'
