// This file is auto-generated by ./bin/rails view_component:stimulus_manifest:update
// Run that command whenever you add a new controller in ViewComponent

import { application } from "../javascript/controllers/application"

import Buyers__RfpScoresComponent__RfpScoresController from "./buyers/rfp_scores_component/rfp_scores_controller"
application.register("buyers--rfp-scores-component--rfp-scores", Buyers__RfpScoresComponent__RfpScoresController)

import FlashComponent__FlashController from "./flash_component/flash_controller"
application.register("flash-component--flash", FlashComponent__FlashController)

import Buyers__ScorePresets from "./buyers/score_presets/controller"
application.register("buyers--score-presets", Buyers__ScorePresets)
